import React from 'react';

const ContactUs = () => {
  return <div>
      <h1>Contact Us</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis omnis officiis fuga commodi maiores excepturi iusto possimus eos, distinctio veniam voluptatibus doloribus exercitationem necessitatibus quae quis. Nam praesentium, ab, illo perferendis expedita incidunt harum doloremque quisquam aspernatur suscipit vitae explicabo commodi magni velit maxime culpa molestiae nobis et voluptatum! Labore, quidem magni cumque quas, dignissimos necessitatibus fuga accusamus deserunt non quasi sit consequatur ullam dolorem ea omnis tenetur velit. Culpa illo sunt molestias a fugit, cumque aspernatur voluptas nam! Omnis delectus quo est laudantium provident similique maxime error reprehenderit odit, ipsum pariatur corrupti expedita commodi, unde velit, modi voluptatibus veritatis illum minus esse consectetur veniam dolorem? Minima magnam ratione in ipsum blanditiis. Expedita aperiam officia doloremque facilis perspiciatis iusto! Accusamus aperiam dolorem velit, perferendis inventore cumque temporibus, dolores voluptatum omnis dignissimos, quis obcaecati. Neque, eius ullam quibusdam suscipit sunt excepturi temporibus asperiores quia porro delectus consequatur accusamus, a perspiciatis placeat! Qui autem nostrum omnis molestias possimus vero facere voluptas libero alias exercitationem voluptatum animi similique nam quaerat explicabo, fuga minima? Excepturi neque minima error mollitia suscipit atque eveniet quibusdam asperiores, ut adipisci tenetur corrupti dolorum, obcaecati tempora distinctio cumque possimus ad debitis ducimus, sapiente iusto dolorem! Sunt molestiae eligendi perferendis ea assumenda deleniti inventore, quaerat vitae fugit maiores omnis voluptas eveniet quam voluptates obcaecati deserunt eum perspiciatis. Voluptatibus saepe dignissimos ad nostrum, unde eos quas sequi deleniti quos magni! Atque iure, necessitatibus optio veritatis dignissimos sequi consequatur animi, suscipit ex culpa doloribus fuga officia, commodi in dolorum expedita consequuntur architecto voluptatem quibusdam tempora alias? Quasi repellat sapiente soluta maxime, aliquid necessitatibus dolor saepe dolorum tenetur facere? Numquam, aliquam dolorum repellendus rerum alias illo corporis. Molestiae illo ex corrupti magni, at est beatae, praesentium adipisci tempora obcaecati libero necessitatibus. Deleniti iure odit in accusamus mollitia ipsam saepe culpa facilis quaerat praesentium.</p>
  </div>;
};

export default ContactUs;
